apiVersion: v1
kind: Secret
metadata:
  name: "dockerhub-creds"
  labels:
    "jenkins.io/credentials-type": "usernamePassword"
  annotations:
    "jenkins.io/credentials-description" : "credentials from Kubernetes"
type: Opaque
stringData:
  username: name  
  password: pass
